KusionStack/karpor

- README.md
> docs: update link in readme

- ui/public/index.html
- ui/src/components/layout/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/nodeLabel.tsx
/kind refactor
optimize some experience issues again
Fixes #
> refactor(ui): optimize some experience issues again

- ui/src/components/sqlSearch/index.tsx
- ui/src/pages/insight/components/insightTabs/styles.module.less
/kind bug
fix wrong scroll on search box
> fix(ui): wrong scroll on search box

- ui/src/pages/insight/components/card/styles.module.less
- ui/src/pages/insight/components/insightTabs/styles.module.less
/kind bug
Fix the display problem of insight page on the Apple M3 chip:
> fix(ui): the display problem of insight page on the Apple M3 chip

- pkg/core/entity/resource_group.go
- pkg/core/entity/resource_group_rule_test.go
- pkg/core/entity/resource_group_test.go
- pkg/core/manager/cluster/manager_test.go
/kind test
Supplementary ResourceGroup-related unit tests. Increase coverage to 70%+.
> test: supplementary ResourceGroup-related unit tests

- README.md
Refine contribute part in readme, and add Community tasks | 新手任务清单 🎖︎.
> docs: refine contribute part in readme

- README-zh.md
Add Chinese Readme documentation
> docs: add readme-zh.md

- ui/src/components/sqlSearch/index.tsx
- ui/src/pages/search/index.tsx
- ui/src/utils/constants.ts
/kind refactor
Fix some experiences problmes.
> fix(ui): some experiences problmes

- .github/workflows/check.yaml
- .github/workflows/release.yaml
/kind bug
Fix the issue where the previous tag cannot be found in ci.
> fix: could't find preview tags in ci

- .all-contributorsrc
- README-zh.md
- README.md
Add a new contributor introduction to readme, welcome! @Paradiesvogel7
> docs: add a new contributor to readme, welcome!

- README-pt.md
It adds a Portuguese translation to the README.md file
As discussed in [KusionStack#468](https://github.com/KusionStack/karpor/issues/468)
I started small with the README file. If you need any changes
or have any improvements, let me know
Related issues #468
> docs(lang): translated README to Portuguese

- .all-contributorsrc
- README-pt.md
- README-zh.md
- README.md
Add a new contributor intro of virtually-stray to readme.
> docs: add a new contributor intro of virtually-stray to readme

- ui/src/components/sqlSearch/index.tsx
- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/zh.json
- ui/src/pages/result/index.tsx
/kind bug
Fix missing placeholder text in i18n files.
> fix: missing placeholder text in i18n files

- ui/src/components/layout/index.tsx
- ui/src/index.tsx
- ui/src/utils/constants.ts
/kind refactor
Easier to add new language for i18n of Web UI.
> refactor(ui): easier to add new language for i18n

- README.md
Refine readme again. Update the introduction, highlight and images.
> docs: refine readme, update intro, highlight and images

- SECURITY-pt.md
Adds a translation to SECURITY.md as discussed in [#468](https://github.com/KusionStack/karpor/issues/468)
Another small change. I'll be translating the UI next.
Related issues [#468](https://github.com/KusionStack/karpor/issues/468)
> docs(lang): translated SECURITY.md to Portuguese

- README-pt.md
- README-zh.md
- README.md
Add multi language links to readme.
References:
- https://github.com/sharkdp/bat
- https://github.com/rustdesk/rustdesk
> docs: add multi language links to readme

- README-pt.md
- README-zh.md
- Update README-zh.md with latest content.
- Fix wrong image links in READM-pt.md
> docs: update README-zh.md with latest content

- ui/src/pages/insight/index.tsx
/kind bug
fix missing i18n key
> fix(ui): missing i18n key

- README-pt.md
- README-zh.md
- README.md
/kind chore
format markdown
Fixes #
> docs: format markdown

- .all-contributorsrc
- README-pt.md
- README-zh.md
- README.md
> docs: add new contributor SparkYuan

- README-zh.md
Fix inappropriate link in README-zh.md
Fixes #
> fix: inappropriate link in README-zh.md

- README-pt.md
- README-zh.md
- README.md
/kind refactor
updated demo video in README.
Fixes #
> refactor: update karpor demo video in README

- README-pt.md
- README-zh.md
- README.md
New video will play well on most browsers.
Fixes #
> fix: use h264 for video encoding to improve compatibility

- README-pt.md
- README-zh.md
- README.md
> docs: simplify emoji in readme

- ui/src/components/layout/index.tsx
/kind refactor
Optimize version number box style.
> refactor(ui): optimize version number box style

- README-zh.md
> docs: update intro in README-zh

- ui/src/locales/zh.json
/kind refactor
fix inappropriate zh copy writing when cluster registry
> fix(ui): inappropriate zh copy writing when cluster registry

- pkg/core/handler/resourcegrouprule/resource_group_rule.go
/kind refactor
optimize list resource group rules api response
> refactor(server): optimize list resource group rules api response

- ui/src/pages/insight/components/quotaContent/quotaCard/index.tsx
- ui/src/pages/insight/index.tsx
- ui/src/utils/request.ts
/kind refactor
add auto jump to registry page when empty cluster
> refactor(ui): add auto jump to registry page when empty cluster

- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/pt.json
- ui/src/locales/zh.json
- ui/src/pages/insight/index.tsx
- ui/src/utils/request.ts
/kind cleanup
add i18n of message of empty cluste
Fixes #
> refactor(ui): add i18n of message of empty cluster

- .all-contributorsrc
- README-pt.md
- README-zh.md
- README.md
Add new contributor rajeshkio, welcome!
> docs: add new contributor rajeshkio, welcome!

- hack/cert-generator/generator/generator.go
/kind bug
fix: missing namespace in cert-generator template
Fixes #
> fix: missing namespace in cert-generator template

- cmd/app/options/ai.go
- cmd/app/server.go
- go.mod
- go.sum
- pkg/core/handler/search/search.go
- pkg/core/manager/ai/manager.go
- pkg/core/route/route.go
- pkg/infra/ai/azureopenai.go
- pkg/infra/ai/huggingface.go
- pkg/infra/ai/openai.go
- pkg/infra/ai/prompts.go
- pkg/infra/ai/types.go
- pkg/kubernetes/registry/types.go
/kind feature
support an AI backend service that other modules can use to access AI language models.
> feat: support ai backends

- pkg/version/VERSION
/kind chore
Bump version file to default version.
> chore: bump version file to default version

- ui/src/pages/insightDetail/group/index.tsx
/kind refactor
adjust detail api call timing
Fixes #
> refactor(ui): adjust detail api call timing

- .goreleaser/.goreleaser-dev.yml
/kind chore
fix missing gen-version in goreleaser-dev
> chore: fix missing gen-version in goreleaser-dev

- ui/.gitignore
- ui/package.json
- ui/src/components/layout/index.tsx
- ui/src/components/sqlSearch/index.tsx
- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/pt.json
- ui/src/locales/zh.json
- ui/src/pages/cluster/add/index.tsx
- ui/src/pages/cluster/certificate/index.tsx
- ui/src/pages/cluster/index.tsx
- ui/src/pages/insight/components/ruleForm/index.tsx
- ui/src/pages/insight/index.tsx
- ui/src/pages/insightDetail/cluster/index.tsx
- ui/src/pages/insightDetail/components/sourceTable/index.tsx
- ui/src/pages/insightDetail/group/index.tsx
- ui/src/pages/insightDetail/kind/index.tsx
- ui/src/pages/insightDetail/namespace/index.tsx
- ui/src/pages/insightDetail/resource/index.tsx
- ui/src/pages/login/index.tsx
- ui/src/pages/login/styles.module.less
- ui/src/pages/result/index.tsx
- ui/src/router/index.tsx
- ui/src/store/modules/globalSlice.ts
- ui/src/utils/request.ts
/kind refactor
optimize ui for authn
> refactor(ui): optimize ui for authn

- ui/src/locales/en.json
- ui/src/locales/zh.json
adjust copy writing of i18n
Fixes #
> docs: adjust copy writing of i18n

- .all-contributorsrc
- README-pt.md
- README-zh.md
- README.md
add new contributor z1cheng, welcome! 🎉
> docs: add new contributor z1cheng, welcome!

- cmd/app/server.go
/kind feature
to support login
Fixes #
> feat: optimize args for signing token

- ui/src/components/layout/index.tsx
- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/pt.json
- ui/src/locales/zh.json
- ui/src/pages/cluster/add/index.tsx
- ui/src/pages/cluster/certificate/index.tsx
- ui/src/pages/insight/index.tsx
- ui/src/pages/login/index.tsx
- ui/src/pages/login/styles.module.less
/kind refactor
this PR fixed some ui bugs, and improves user experiense for login
Fixes #
> refactor(ui): optimize ui for authn and fix some ui bug

- Makefile
- ui/src/components/layout/index.tsx
/kind refactor
Adjust ui to adapt github-badge flag and refine makefile.
> refactor: adjust ui to adapt github-badge flag, refine makefile

- config/default-anonymous-rbac.yaml
- config/default-karpor-admin-rbac.yaml
- config/default-karpor-guest-rbac.yaml
- config/embed.go
/kind feature
add build-in clusterrole: karpor-admin and karpor-guest
Fixes #
> feat: add more built-in clusterrole

- ui/src/pages/cluster/add/index.tsx
- ui/src/pages/cluster/certificate/index.tsx
- ui/src/utils/request.ts
/kind bug
Handle code 401 and 403 with different logic in front/UI
Fixes #
> fix: UI handle code 401 and 403 separately

- .goreleaser/.goreleaser-dev.yml
/kind chore
fix wrong image build on dev release pipeline.
> fix(ci): wrong image build on dev release pipeline

- .all-contributorsrc
- README-pt.md
- README-zh.md
- README.md
Add new contributor iamryanchia, welcome! 🎉
Fixes #
> docs: add new contributor iamryanchia, welcome!

- ui/src/components/layout/style.module.less
- ui/src/pages/cluster/add/styles.module.less
- ui/src/pages/cluster/index.tsx
- ui/src/pages/cluster/styles.module.less
- ui/src/pages/login/styles.module.less
- ui/src/utils/request.ts
> fix: token

- .github/CODEOWNERS
- ui/src/pages/login/styles.module.less
/kind refactor
refine login box style
Fixes #
> refactor(ui): refine login box style

- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/pt.json
- ui/src/locales/zh.json
> chore: improve token guide in dashboard

- config/default-anonymous-rbac.yaml
- config/default-karpor-admin-rbac.yaml
- config/default-karpor-guest-rbac.yaml
/kind chore
add RBAC rules of livez and readyz
Fixes #
> chore: add livez and readyz in default RBAC

- README-pt.md
- README-zh.md
- README.md
add artifacthub badge to readme
Fixes #
> docs: add artifacthub badge to readme

- pkg/util/certgenerator/generator.go
/kind bug
fix missing protocol in hub cluster config template.
> fix: missing protocol in hub cluster config template

- ui/src/pages/insightDetail/namespace/index.tsx
- ui/src/pages/insightDetail/resource/index.tsx
/kind bug
Fix wrong api address
Fixes #
> fix(ui): wrong api address

- pkg/syncer/source.go
/kind bug
If we don't handle DeletedFinalStateUnknown object, the document in ES associated with the deleted resource will be left forever.
Fixes #
> fix(syncer): handle DeletedFinalStateUnknown objects

- README.md
Update current status in readme.md.
> docs: update current status

- ui/src/pages/insightDetail/resource/index.tsx
/kind bug
Fix language switching log does not take effect
Fixes #
> fix:  language switching log does not take effect

- README-pt.md
- README-zh.md
- README.md
This PR optimizes the badges in the README file to improve readability and visual appeal.
Fixes #
> docs(readme): optimize badges in readme

- ui/package.json
- ui/src/pages/cluster/add/index.tsx
- ui/src/utils/confetti.ts
/kind feature
This PR optimizes the registration success experience by adding a confetti effect. This enhancement improves user engagement and provides a more celebratory feel upon successful registration.
Fixes #
> feat(cluster): optimize registration success experience (add confetti effect)

- ui/src/pages/insightDetail/cluster/index.tsx
- ui/src/pages/insightDetail/group/index.tsx
- ui/src/pages/insightDetail/namespace/index.tsx
> fix: single resource show event tab

- go.mod
/kind chore
fix "go list -m all" execution
Fixes #
> chore: fix "go list -m all" execution

- ui/src/pages/insightDetail/components/podLogs/index.tsx
- ui/src/utils/request.ts
> feat: control connect status by settings

- .all-contributorsrc
- README-pt.md
- README-zh.md
- README.md
This PR adds Raj to the contributors list. The details are as follows:\n- **Name**: Raj\n- **Contribution**: Added to the contributors list to acknowledge their contributions to the project.
Fixes #
> docs(contributors): add rajp152k to contributors list

- ui/src/pages/insightDetail/cluster/index.tsx
- ui/src/pages/insightDetail/components/podLogs/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/style.module.less
- ui/src/pages/insightDetail/group/index.tsx
- ui/src/pages/insightDetail/namespace/index.tsx
- ui/src/pages/insightDetail/resource/index.tsx
> fix: topology g6 interactive

- pkg/core/manager/insight/summary.go
- pkg/core/manager/insight/types.go
- ui/src/hooks/useClusterLatency.ts
- ui/src/pages/cluster/components/clusterCard/index.tsx
- ui/src/pages/insightDetail/components/sourceTable/index.tsx
- ui/src/pages/insightDetail/components/summaryCard/index.tsx
/kind feature
This PR shows cluster latency in summary card and cluster card.
---------
Fixes https://github.com/KusionStack/karpor/issues/457
> feat: display cluster latency

- ui/src/pages/insightDetail/components/topologyMap/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/style.module.less
- ui/src/utils/request.ts
> fix: g6 topology fit center

- ui/src/pages/insightDetail/components/sourceTable/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/index.tsx
> fix: topology graph blue dot

- ui/src/components/yaml/index.tsx
- ui/src/components/yaml/styles.module.less
- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
- ui/src/pages/insightDetail/components/topologyMap/style.module.less
/kind refactor
This PR simplifies the AI enabled check and improves code formatting in the YAML-related code.
Key changes include:
- Simplified the logic for checking if AI is enabled, making it more readable and maintainable.
- Improved code formatting to adhere to consistent style guidelines, enhancing overall code quality.
Fixes #
> refactor(yaml): simplify AI enabled check and improve code formatting

- ui/src/components/yaml/index.tsx
- ui/src/components/yaml/styles.module.less
- ui/src/pages/insightDetail/components/eventAggregator/index.tsx
- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
- ui/src/pages/insightDetail/components/podLogs/index.tsx
- ui/src/pages/insightDetail/components/podLogs/styles.module.less
> refactor(ui): pretty ai analysis windows again

- ui/src/components/yaml/styles.module.less
- ui/src/pages/insightDetail/components/eventAggregator/index.tsx
- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
- ui/src/pages/insightDetail/components/exceptionList/style.module.less
- ui/src/pages/insightDetail/components/podLogs/styles.module.less
> refactor(ui): ai interpret style pretty

- config/default-anonymous-rbac.yaml
/kind bug
add ai analyze apis to clusterrole anonymous
Fixes #
> fix: allow anonymous user to get AI analyze

- ui/src/components/yaml/styles.module.less
- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
- ui/src/pages/insightDetail/components/exceptionList/index.tsx
- ui/src/pages/insightDetail/components/exceptionList/style.module.less
- ui/src/pages/insightDetail/components/exceptionStat/style.module.less
- ui/src/pages/insightDetail/components/podLogs/styles.module.less
- ui/src/pages/insightDetail/components/summaryCard/index.tsx
- ui/src/pages/insightDetail/components/summaryCard/styles.module.less
/kind refactor
This PR updates the styling of the `interpret_panel` component to enhance its visual design and user experience. The changes include:
- Beautify ai interpret panel styling
- Improve re-scan and collapse button UI interactions
- Beautify font style in summary and issue card
These improvements make the component more engaging and aesthetically pleasing.
Old:
Now:
Fixes #
> refactor(ui): beautify ai interpret panel styling

- README-pt.md
- README-zh.md
- README.md
This PR updates the README files to improve the visual representation of the AI diagnostics feature:
- Replaces the 'coming-soon' placeholder image with the actual AI diagnostics image
- Added Product Hunt badge
- Ensures consistency across different language versions of the README
These changes provide a more accurate and informative preview of the AI diagnostics feature for users.
Fixes #
> docs: add AI diagnostics image, ProductHunt vote badge to README

- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
- ui/src/pages/insightDetail/components/exceptionList/style.module.less
> refactor(ui): pretty ai analysis panel style

- .github/workflows/milestone-summary.yml
/kind feature
This PR introduces a new GitHub Actions workflow for milestone planning. 
Key changes include:
- Added a new workflow that triggers on milestone and issue events.
- Utilized the `auto-milestone-summary-action` to automate the generation of milestone planning summaries.
- Defined categories to organize and label issues effectively, improving project management and tracking.
This workflow is essential for automating the planning process, ensuring that milestones are consistently and efficiently managed.
Fixes #
> chore(ci): add milestone planning workflow

- ui/src/utils/request.ts
> fix: insight edit function api method

- .github/workflows/milestone-summary.yml
/kind chore
- Added 'chore', 'security', 'testing', and 'logistics' labels to the list of allowed labels in the milestone summary workflow.
- This change ensures that the workflow correctly processes issues and pull requests tagged with these new labels.
Fixes #
> chore(ci): add new labels to milestone summary workflow

- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
> refactor(ui): pretty event ai style

- ui/src/pages/insightDetail/components/eventAggregator/index.tsx
- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
/kind bug
Fix the inconsistency in height between the AI window and the event table
> fix(ui): inconsistency in height between the AI window and the event table

- ui/public/index.html
/kind refactor(ui)
This PR updates the website's SEO and social sharing meta tags to improve visibility and user engagement. The changes include:
- Adding Open Graph and Twitter Card meta tags to enhance the appearance of shared links on social media platforms.
- Updating the meta description to better highlight the advanced search and insight capabilities of the platform.
- Refining the title to emphasize the intelligence features for Kubernetes, making it more appealing to the target audience.
Fixes #
> refactor(ui): update SEO and social sharing meta tags

- README-pt.md
- README-zh.md
- README.md
- ui/public/index.html
Update demo video in readme
Fixes #
> docs: update demo video in readme

- README.md
This PR updates the README to reflect the current project status and provides the correct link for community discussions.
- Updates the current status to reflect the v0.7.0 milestone
- Updates the discussion link to the latest thread
Fixes #
> docs: update README with v0.7.0 milestone

- README-ja.md
- README-pt.md
- README.md
- SECURITY-ja.md
I created Japanese translated documents.
> docs: add Japanese documents

- .all-contributorsrc
- README-ja.md
- README-pt.md
- README-zh.md
- README.md
This PR updates the documentation to:
- Add Ikko Eltociear Ashimine to the contributor list in all README files
- Include README-ja.md in the list of files in .all-contributorsrc
These changes ensure that the documentation accurately reflects the current contributors and includes all relevant README files.
Fixes #
> docs: add new contributor eltociear

- README-zh.md
update outdate Chinese README
Fixes #
> docs: update Chinese README

- .all-contributorsrc
- README-ja.md
- README-pt.md
- README-zh.md
- README.md
This PR:
- Updates the `.all-contributorsrc` file to include Cookie's contributions.
- Adds Cookie's profile to the following README files: `README.md`, `README-ja.md`, `README-pt.md`, and `README-zh.md`.
This change acknowledges Cookie's contributions to the project by adding their profile to the list of contributors in the documentation.
Fixes #
> docs: add new contributor Cookie to README files

- api/openapispec/docs.go
- api/openapispec/swagger.json
- api/openapispec/swagger.yaml
- docs/api.md
- pkg/core/route/route.go
Include /server-configs endpoint details in Swagger documentation. 
Missing line breaks in the description field of docs/api.md.
Fixes #
> docs: add /server-configs

- .all-contributorsrc
- README-ja.md
- README-pt.md
- README-zh.md
- README.md
Add new contributor @jinjiaKarl , welcome!
Fixes #
> docs: add new contributor jinjiaKarl, welcome!

- ui/craco.config.ts
- ui/package.json
/kind bug
fix build error of node v23
Fixes #
> fix(ui): build error of node v23

- cmd/karpor/app/options/ai.go
- pkg/infra/ai/azureopenai.go
- pkg/infra/ai/huggingface.go
- pkg/infra/ai/openai.go
- pkg/infra/ai/types.go
- pkg/kubernetes/registry/types.go
/kind feature
add llm api proxy parameters
Fixes #736
> feat: add llm api proxy parameters

- config/default-sync-strategy.yaml
/kind feature
For users to search for ingress resources
Fixes #709
> feat(syncer): add ingress(networking.k8s.io/v1) to watch list

- Makefile
> chore: optimize Makefile with automatic cleanup and cross-platform build

- docs/cli/karpor.md
- pkg/infra/ai/azureopenai.go
- pkg/infra/ai/deepseek.go
- pkg/infra/ai/deepseek_test.go
- pkg/infra/ai/types.go
Introduces Deepseek as a new AI provider with comprehensive implementation:
- Support Deepseek as New AI Backend in Karpor
- Created corresponding test suite for Deepseek AI client
https://github.com/KusionStack/karpor/issues/789
> feat(ai): Support Deepseek as New AI Backend in Karpor

- cmd/karpor/app/mcp.go
- cmd/karpor/main.go
/kind feature
initializes the development process for an MCP SSE server for elasticsearch storage backend
pertains to #658
> feat(MCP): mcp SSE init (elasticsearch storage)

- README-ja.md
- README-pt.md
- README-zh.md
- README.md
- docs/conventions/test-conventions.md
- pkg/README.md
> docs: remove invalid links

- pkg/syncer/reconciler.go
- pkg/syncer/reconciler_test.go
- pkg/syncer/single_cluster_sync_manager.go
- pkg/syncer/single_cluster_sync_manager_test.go
/kind feature
Support wildcard resource
Fixes #817
> feat: support wildcard resource
