- go.mod
/kind bug
Fix missing replace for hack/cert-generator. Otherwise, an error will be reported:
```bash
go: github.com/KusionStack/karpor/hack/cert-generator@v0.3.23-alpha.2: module github.com/KusionStack/karpor@v0.3.23-alpha.2 found, but does not contain package github.c
om/KusionStack/karpor/hack/cert-generator
```
> fix: missing replace for hack/cert-generator

- Makefile
/kind chore
Add `GOARCH` option to build-ralated target in makefile
> chore: add GOARCH option to build-related target in makefile

- .gitignore
/kind bug
Fix missing ui/build/.gitkeep for correct build:
> fix(build): missing ui/build/.gitkeep for correct build

- cmd/app/options/core_options.go
- pkg/kubernetes/registry/types.go
/kind feature
Add `--github-badge` flag to core options.
Prepare for #501
> feat: add --github-badge flag to core options

- config/default-rbac.yaml
/kind bug
Fix missing insight authorize in default rbac config. Nice catch @ruquanzhao !
> fix: missing insight authorize in default rbac config

- ui/src/pages/insightDetail/group/index.tsx
/kind bug
Fix wrong topology resources list when switching cluster.
> fix(ui): wrong topology resources list when switch cluster

- Makefile
- pkg/core/handler/cluster/cluster.go
- pkg/core/manager/cluster/manager.go
- pkg/core/manager/cluster/manager_test.go
- pkg/core/manager/cluster/types.go
- pkg/core/manager/cluster/util.go
/kind refactor
If uploading a token based kubeconfig, error reported as invalid kubeconfig.
In fact, token based kubeconfig is general usage in many cases.
ref: https://kb.leaseweb.com/products/kubernetes/users-roles-and-permissions-on-kubernetes-rbac/create-a-token-based-kubeconfig
> fix: Add support to manage token based auth

- pkg/core/handler/renders.go
- pkg/core/handler/resourcegroup/resource_group.go
/kind refactor
Optimize response of list resource groups api. When the resource groups not found, the status code should be 404 and the response.success should be true.
> refactor(server): optimize response of list resource groups api

- ui/src/components/layout/index.tsx
- ui/src/store/modules/globalSlice.ts
/kind feature
Control whether the Github logo is displayed in UI
Close #501
> feat(ui): control whether the Github logo is displayed

- pkg/core/handler/util.go
- pkg/core/manager/cluster/manager.go
- pkg/core/manager/insight/resource.go
- pkg/version/VERSION
/kind feature
把yaml中的managedFields字段设置为空,优化体验
Fixes #461
> feat: ignore the k8s automatic injection fields such as managedFields

- pkg/syncer/transform/transform.go
/kind bug
The underlying type of `dest` is `*unstructured.Unstructured`, and the address operator makes the return value be a pointer to a pointer, which causes keyFunc `DeletionHandlingMetaNamespaceKeyFunc` to return errors.
Fixes #
> fix(syncer): wrong address operator on transform Patch func

- ui/src/pages/login/index.tsx
Fix wrong link for create token guide.
Fixes #520
> fix: wrong link for create token guide

- .github/workflows/release.yaml
#547
/kind feature
Governance: Automatically update the appVersion in the Chart when released
Fixes #547
> feat: automatically update the appVersion in Chart when release new version

- pkg/util/certgenerator/generator.go
/kind bug
Fix wrong endpoint in generated hub cluster config:
And fix #608
> fix: wrong endpoint in generated hub cluster config

- ui/src/components/sqlSearch/index.tsx
- ui/src/locales/de.json
- ui/src/locales/en.json
- ui/src/locales/pt.json
- ui/src/locales/zh.json
- ui/src/pages/insightDetail/components/tagVariableSizeList/index.tsx
- ui/src/pages/result/index.tsx
- ui/src/pages/search/index.tsx
- ui/src/utils/constants.ts
- ui/src/utils/tools.ts
> feat: search by natural language

- pkg/syncer/single_cluster_sync_manager.go
- pkg/syncer/source.go
- pkg/syncer/transform/tmpl_funcs.go
/kind feature
For example, we have an app named `ray`, and we want to quick search all its events including deployment and pods.
we can add label `app=ray` to all its events, then we can just type `` where kind = 'Event' and  `labels.app` = "ray" `` to search all related events.
```yaml
---
apiVersion: search.karpor.io/v1beta1
kind: TransformRule
metadata:
name: for-events
spec:
type: patch
valueTemplate: |
{{- $ref := (objectRef .Object.involvedObject.apiVersion .Object.involvedObject.kind .Object.involvedObject.namespace .Object.involvedObject.name) -}}
[
{ "op": "add", "path": "/metadata/labels", "value": { "app": "{{ index $ref.Object.metadata.labels "app" }}" } }
]
---
apiVersion: search.karpor.io/v1beta1
kind: SyncRegistry
metadata:
name: events-sync-rule
spec:
clusters:
- "*" …
```
> feat(syncer): supports users to group related resources by adding same label

- pkg/syncer/syncer.go
/kind bug
The cluster template functions has been registered but not used.
Fixes #
> fix: fix tmpl functions registered but not used

- pkg/core/handler/search/formatter.go
- pkg/core/handler/search/formatter_test.go
- pkg/core/handler/search/search.go
- pkg/core/manager/search/types.go
- pkg/syncer/source.go
- pkg/syncer/utils/selector.go
- pkg/syncer/utils/selector_test.go
- pkg/util/jsonpath/fields.go
- pkg/util/jsonpath/fields_test.go
/kind feature
The current search interface returns the full data stored in Elasticsearch to the front-end. The front-end needs to perform an operation to extract certain fields from the complete object and display them to the user.
This PR moves the field extraction operation to the back-end, similar to `kubectl get -o 'custom-columns=<spec>`. This will parameterize the data returned by the back-end, simplify the integration workload for third-party front-ends, and reduce the amount of data transmitted to the front-end.
For example:
`curl -k 'https://127.0.0.1:7443/rest-api/v1/search?query=select+*+from+resources+where+kind+%3D+%27Pod%27+and+name+%3D+%27karpor-syncer-6dfddf556-djn9c%27&pattern=sql&page=1&pageSize=20&format=custom-columns%3DNAME%3Ametadata.name%2CAPI_VERSION%3AapiVersion'` …
> feat: add custom-columns capability

- cmd/karpor/app/options/ai.go
- pkg/core/handler/search/search.go
- pkg/core/manager/ai/manager.go
- pkg/core/manager/ai/types.go
- pkg/core/route/route.go
- pkg/infra/ai/azureopenai.go
- pkg/infra/ai/openai.go
- pkg/infra/ai/types.go
- pkg/kubernetes/registry/types.go
/kind feature
change the AI command line argument to optional
Fixes #551
> feat: change the AI command line argument to optional

- pkg/core/handler/search/search.go
- pkg/core/manager/ai/search.go
- pkg/core/manager/ai/types.go
- pkg/core/manager/ai/util.go
- pkg/core/manager/ai/util_test.go
- pkg/infra/ai/prompts.go
/kind feature
Filter invalid queries for natural language search.
Fixes #556
> feat: filter invalid queries for natural language search

- Makefile
/kind chore
Fix wrong swagger args of gen-api-spec in Makefile
Fixes #
> fix: wrong swagger args of gen-api-spec in Makefile

- ui/package.json
- ui/src/components/yaml/index.tsx
- ui/src/components/yaml/styles.module.less
> feat: yaml module height drag

- pkg/core/entity/resource_group.go
- pkg/core/handler/search/search.go
- pkg/core/manager/insight/resource.go
- pkg/core/manager/search/types.go
- pkg/infra/persistence/elasticsearch/client.go
- pkg/infra/search/storage/elasticsearch/resource.go
- pkg/infra/search/storage/elasticsearch/search.go
- pkg/infra/search/storage/types.go
- pkg/kubernetes/apis/search/types.go
- pkg/kubernetes/apis/search/v1beta1/types.go
- pkg/kubernetes/apis/search/v1beta1/zz_generated.conversion.go
- pkg/kubernetes/generated/openapi/zz_generated.openapi.go
- pkg/syncer/source.go
- pkg/syncer/syncer.go
- pkg/syncer/syncer_test.go
- pkg/syncer/utils/purger.go
- pkg/util/sql2es/convert.go
- pkg/util/sql2es/convert_test.go
- ui/src/pages/insightDetail/components/sourceTable/index.tsx
- ui/src/pages/insightDetail/namespace/index.tsx
- ui/src/pages/insightDetail/resource/index.tsx
- ui/src/pages/result/index.tsx
- ui/src/pages/result/styles.module.less
/kind feature
In the current implementation, the lifecycle of storage data is bound to object in cluster. When an object is deleted in cluster, the associated data in storage will also be cleared.
Events in cluster are retained for one hour by default. As key information for troubleshooting, it is usually hoped that events can be retained for a longer time, which requires karpor to unbind the lifecycle of specific types of resources from cluster.
This PR adds a `remainAfterDeleted` field in the SyncRegistry CRD to control that a certain type of resources remain in storage after being deleted in cluster.
If the user sets `remainAfterDeleted=true` for a type of resource, the user needs to delete the associated data in the storage by himself. Karpor only marks `deleted=true` for storage data …
> feat: soft delete

- .github/workflows/constraint.yaml
- .github/workflows/mlc_config.json
/kind bug
This PR configures markdown-link-check to ignore FOSSA badge URLs that are incorrectly reported as dead links. The links are actually accessible but were being flagged as 404 errors.
Fixes #
> fix: ignore FOSSA badge links in markdown link check

- cmd/karpor/app/options/core_options.go
- cmd/karpor/app/server.go
- pkg/kubernetes/registry/types.go
- ui/src/components/layout/index.tsx
- ui/src/pages/cluster/add/index.tsx
- ui/src/pages/cluster/certificate/index.tsx
- ui/src/pages/login/index.tsx
- ui/src/store/modules/globalSlice.ts
/kind bug
This pr set RBAC authorization off on default.
Fixes #
> feat: add a flag --enable-rbac to control authorization

- Makefile
/kind chore
This PR updates the Makefile to exclude additional directories from test coverage. This is necessary to ensure that irrelevant directories are not included in the test coverage report, which can lead to misleading results and unnecessary noise in the coverage metrics.
Fixes #
> chore: exclude additional directories from test coverage

- README-pt.md
- README-zh.md
- README.md
This PR adds FOSSA and Trendshift badges to the README file. These badges provide additional information about the project's license compliance and code quality, respectively. Including these badges helps users and contributors quickly assess the project's status and encourages transparency.
Fixes #
> docs(README): add FOSSA and Trendshift badges

- ui/src/pages/result/index.tsx
/kind bug
This PR resolves an invalid hook call in the search result page by moving the `useTranslation` hook inside function components, fixing a runtime error caused by incorrect hook usage. It ensures that hooks are only called within React function components.
Fixes #
> fix(ui): resolve invalid hook call in search result page

- ui/src/pages/insightDetail/components/podLogs/index.tsx
- ui/src/pages/insightDetail/components/podLogs/styles.module.less
/kind bug
This PR addresses issues related to log flickering and duplication during Server-Sent Events (SSE) reconnection in the pod logs feature. The changes include:
- **Fix log duplication:**
- Implement robust log deduplication by generating unique log IDs using timestamps and content.
- Prevent duplicate logs from appearing during SSE reconnection.
- Clear logs when settings are changed to avoid stale data.
- **Optimize SSE connection handling:**
- Improve reconnection logic to ensure smoother transitions.
- Prevent UI flickering during reconnection.
- Enhance error handling for connection failures to improve reliability.
- **Enhance log viewer user experience:**
- Improve the settings modal UI and behavior for better usability.
- Modify the download functionality to save only …
> fix(pod-logs): resolve log flickering and duplication during SSE reconnection

- ui/src/pages/insightDetail/components/topologyMap/index.tsx
- ui/src/pages/insightDetail/components/topologyMap/style.module.less
> fix: fix topology graph interactive

- ui/src/pages/insightDetail/components/topologyMap/index.tsx
- ui/src/pages/insightDetail/resource/index.tsx
- ui/src/utils/request.ts
> fix: topology interactive 1223

- ui/src/hooks/usePodStatus.ts
- ui/src/pages/insightDetail/components/sourceTable/index.tsx
- ui/src/pages/insightDetail/components/summaryCard/index.tsx
- ui/src/pages/insightDetail/components/summaryCard/styles.module.less
- ui/src/pages/result/index.tsx
/kind feature
This PR adds Pod status in search result and source tables:
----------––--
Fixes #
> feat: add Status of Pod in search result and source table

- .github/workflows/release.yaml
/kind bug
This PR fixes an issue where the wrong app version was being used when updating the chart.
Specifically:
- Corrects the app version logic in the CI pipeline
- Ensures the correct version is applied during chart updates
Fixes #
> fix(ci): incorrect app version generated in chart updater

- ui/src/pages/result/index.tsx
- ui/src/pages/search/index.tsx
/kind cleanup
disable natural language search tab in search page and result page if AI backend is not configured.
Fixes #
> fix: disable Natural Language Search Tab if AI backend is not configured

- pkg/core/manager/insight/summary.go
/kind bug
This PR addresses an issue where the function fails when the server version cannot be retrieved.
- Adds a default server version string 'v0.0.0-unknown' as a fallback value when an error occurs.
This ensures that the function continues to operate without failing and provides a consistent value in case of errors.
Fixes #
> fix: handle server version error with default value

- pkg/core/middleware/readonly.go
/kind bug
This PR modifies the ReadOnlyMode middleware to allow non-GET requests for URLs ending with '/stream'.
Key changes include:
- Adjusting the middleware logic to permit non-GET requests for paths ending with '/stream'.
- Ensuring streaming endpoints remain functional in read-only mode, addressing a specific use case where streaming data is required.
Fixes #
> fix: allow non-GET requests for paths ending with /stream

- .github/workflows/milestone-summary.yml
/kind chore
This PR extends the GitHub Actions workflow to include 'labeled' and 'unlabeled' events as triggers. 
- Adds support for 'labeled' and 'unlabeled' events in the issue event types.
Fixes #
> chore(ci): add labeled and unlabeled events to issue triggers

- cmd/karpor/app/server.go
- pkg/core/route/route.go
/kind cleanup
- hidden AI backend token in ServerConfig api
- remove `cmdline` and `memstat` in ServerConfig api
Fixes #
> fix: hidden cmdline, memstat and token in serverconfig

- .github/workflows/milestone-summary.yml
/kind chore
- Added 'integration' to the list of categories in the GitHub workflow configuration.
- Ensures that the milestone summary workflow correctly categorizes tasks related to integration.
Fixes #
> chore: add 'integration' to milestone summary categories

- .github/workflows/community-planning-updater.yml
/kind chore
This PR includes the following changes:
- Renames `.github/workflows/milestone-summary.yml` to `.github/workflows/community-planning-updater.yml`
- Updates the action from `elliotxx/auto-milestone-summary-action@v1` to `elliotxx/community-planning-updater@v1`
These changes align the workflow name and action with its intended purpose of updating community planning, improving clarity and maintainability.
Fixes #
> chore(ci): rename community-planning-updater action

- .github/workflows/community-planning-updater.yml
/kind feature
This PR adds support for 'assigned' and 'unassigned' event types to the GitHub Actions workflow.
Key changes include:
- Updated the workflow to trigger on 'assigned' and 'unassigned' events for issues.
- Ensures better automation and responsiveness to issue management activities.
Fixes #
> feat: add assigned and unassigned events to issue triggers

- .all-contributorsrc
- README-ja.md
- README-pt.md
- README-zh.md
- README.md
This PR:
- Updates the `.all-contributorsrc` file to include Adam as a contributor with the 'tool' contribution type.
- Adds Adam to the contributors list in multiple README files (`README.md`, `README-ja.md`, `README-pt.md`, and `README-zh.md`).
- Thanks to the [Karpor Chart's bug fix](https://github.com/KusionStack/charts/pull/100) for the Adam!
This change ensures proper recognition of Adam's contributions to the project's tools and maintains consistency across all documentation files.
Fixes #
> docs: welcome new contributor Adam

- pkg/infra/search/storage/elasticsearch/resource.go
> fix: the index out of range when es resp is empty

- pkg/infra/search/storage/elasticsearch/resource.go
- ui/src/pages/insightDetail/components/eventAggregator/styles.module.less
- ui/src/pages/insightDetail/components/exceptionList/style.module.less
/kind style
This PR addresses linting and formatting issues to improve code readability and maintain consistency with linting rules. 
- Corrected indentation in Go code to resolve golangci-lint issues.
- Reformatted gradient definitions in LESS for better readability.
- Removed an unnecessary line in exceptionList styles.
Fixes #
> fix: linting and formatting issues

- .github/workflows/community-task-updater.yml
/kind chore
This PR refactors the CI/CD process by making the following changes:
- Renames the job from 'plan' to 'osp-run' to better reflect its purpose.
- Updates the action from 'community-planning-updater' to 'osp-action' for improved functionality.
- Introduces a new workflow 'community-task-updater.yml' to manage community tasks more effectively.
These changes enhance the project's ability to manage and onboard new contributors by streamlining the workflow and improving task management.
Fixes #
> chore(ci): add community planning and task updater workflow, power by osp

- .github/workflows/community-planning-updater.yml
- .github/workflows/community-task-updater.yml
/kind chore
**Tested without any problems, officially enabled OSP automatic updates (Planning and Community Tasks).**
This PR removes the `--dry-run` option from OSP-related CI workflows:
- Removes `--dry-run` from the community planning workflow
- Removes `--dry-run` from the community task workflow
The workflows will now make live changes as originally intended. The `--dry-run` option was likely used for testing and is no longer necessary.
Fixes #
> chore(ci): remove dry-run from OSP-related CI workflows

- .github/workflows/community-planning-updater.yml
/kind chore
This PR adds the 'growth' category label to the planning updater workflow in GitHub Actions.
Key changes:
- Updated the workflow configuration to include 'growth' as a category label
- Enables better organization and tracking of issues or features related to growth initiatives
Fixes #
> chore(ci): add 'growth' category label to planning updater workflow

- .github/workflows/community-planning-updater.yml
- .github/workflows/community-task-updater.yml
/kind chore
This PR adds the '--yes' flag to osp-related workflow commands to automate the confirmation process.
- Added '--yes' to the 'plan' command in `community-planning-updater.yml`
- Added '--yes' to the 'onboard' command in `community-task-updater.yml`
This change improves workflow efficiency by eliminating the need for manual confirmation during execution.
Fixes #
> chore(ci): add --yes flag to osp-related workflow

- Makefile
- api/openapispec/docs.go
- api/openapispec/swagger.json
- api/openapispec/swagger.yaml
- docs/api.md
- pkg/core/handler/search/search.go
- ui/src/pages/insightDetail/components/sourceTable/index.tsx
/kind feature
/kind chore
- Add Search Functionality to Resource List in Insights Page
- Update Makefile to use full path for swag and swagger commands
https://github.com/KusionStack/karpor/issues/679
> feat(search): Add Search Functionality to Resource List in Insights Page

- .golangci.yml
- Makefile
- cmd/karpor/app/options/ai.go
- pkg/infra/ai/deepseek.go
- pkg/version/VERSION
/kind refactor
This PR introduces the following changes:
- Updated the Makefile to use `ifndef` for the SKIP_UI_BUILD flag, improving the build process.
- Adjusted AI options to handle default model settings more effectively.
- Added a default model for the Deepseek client to ensure better defaults.
- Remove buildssa and fieldalignment linters in disable
These changes aim to enhance the build process and AI configuration handling, making the system more robust and user-friendly.
Fixes #
> feat(ai): added a default model for the Deepseek client

- ui/src/components/yaml/index.tsx
- ui/src/locales/en.json
- ui/src/pages/insightDetail/cluster/index.tsx
Add refresh button on YAML tab to allow users manually refresh YAML data in cluster management view. 
This improves user experience by providing direct control over YAML data refresh.
Fixes #712
> feat(yaml): add refresh button & refresh when switch the tab
